# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 1268)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color:rgb(234, 234, 234)\n"
"\n"
"\"QMenuBar{background-color:transparent;}\"/*设置背景色，跟随背景色*/                           \n"
"\"QMenuBar::selected{background-color:transparent;}\"/*设置菜单栏选中背景色*/\n"
"\"QMenuBar::item{font-size:12px;font-family:Microsoft YaHei;color:rgba(255,255,255,1);}\"/*设置菜单栏字体为白色，透明度为1（取值范围0.0-255）*/\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setStyleSheet("background-color:rgb(234, 234, 234)")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame2)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setStyleSheet("QMainWindow{\n"
"background-color:rgb(234, 234, 234)\n"
"}\n"
"QLabel{\n"
"font: bold 18px \"Microsoft YaHei\";\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(0, 170, 255);\n"
"font: bold 19px \"Microsoft YaHei\";\n"
"color: white;\n"
"border-radius: 10px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-color: rgb(125, 255, 39);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    padding: 2px;\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    padding: 2px;\n"
"    background-color: rgb(0, 170, 127);\n"
"}")
        self.page1.setObjectName("page1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame4 = QtWidgets.QFrame(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.frame4.sizePolicy().hasHeightForWidth())
        self.frame4.setSizePolicy(sizePolicy)
        self.frame4.setStyleSheet("\n"
".QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border:0px\n"
"}")
        self.frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame4.setObjectName("frame4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.frame_5 = QtWidgets.QFrame(self.frame4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("    .QFrame{\n"
"            border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0, 168, 252);\n"
"    background-color: white;\n"
"    color: #d3dae3;\n"
"    }\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.m1_p3 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.m1_p3.sizePolicy().hasHeightForWidth())
        self.m1_p3.setSizePolicy(sizePolicy)
        self.m1_p3.setMinimumSize(QtCore.QSize(500, 0))
        self.m1_p3.setStyleSheet("")
        self.m1_p3.setText("")
        self.m1_p3.setScaledContents(False)
        self.m1_p3.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_p3.setObjectName("m1_p3")
        self.horizontalLayout_5.addWidget(self.m1_p3)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_5.addWidget(self.frame4)
        self.frame3 = QtWidgets.QFrame(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.frame3.sizePolicy().hasHeightForWidth())
        self.frame3.setSizePolicy(sizePolicy)
        self.frame3.setStyleSheet("\n"
".QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border:0px\n"
"}\n"
"\n"
"")
        self.frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setStyleSheet("    .QFrame{\n"
"            border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0, 168, 252);\n"
"    background-color: white;\n"
"    color: #d3dae3;\n"
"    }\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.m1_p1 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.m1_p1.sizePolicy().hasHeightForWidth())
        self.m1_p1.setSizePolicy(sizePolicy)
        self.m1_p1.setStyleSheet("")
        self.m1_p1.setText("")
        self.m1_p1.setScaledContents(False)
        self.m1_p1.setObjectName("m1_p1")
        self.verticalLayout_4.addWidget(self.m1_p1)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("    .QFrame{\n"
"            border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0, 168, 252);\n"
"    background-color: white;\n"
"    color: #d3dae3;\n"
"    }\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.m1_p2 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.m1_p2.sizePolicy().hasHeightForWidth())
        self.m1_p2.setSizePolicy(sizePolicy)
        self.m1_p2.setStyleSheet("")
        self.m1_p2.setText("")
        self.m1_p2.setScaledContents(False)
        self.m1_p2.setObjectName("m1_p2")
        self.verticalLayout_6.addWidget(self.m1_p2)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_5.addWidget(self.frame3)
        self.frame_11 = QtWidgets.QFrame(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setStyleSheet("\n"
".QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border:0px\n"
"}\n"
"\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.m1_run1 = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m1_run1.sizePolicy().hasHeightForWidth())
        self.m1_run1.setSizePolicy(sizePolicy)
        self.m1_run1.setMinimumSize(QtCore.QSize(200, 45))
        self.m1_run1.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.m1_run1.setFont(font)
        self.m1_run1.setStyleSheet("")
        self.m1_run1.setObjectName("m1_run1")
        self.verticalLayout_9.addWidget(self.m1_run1)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setMinimumSize(QtCore.QSize(600, 600))
        self.page2.setObjectName("page2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("QLabel{\n"
"font: bold 14px \"Microsoft YaHei\";\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(0, 170, 255);\n"
"font: bold 19px \"Microsoft YaHei\";\n"
"color: white;\n"
"border-radius: 10px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-color: rgb(125, 255, 39);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    padding: 2px;\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    padding: 2px;\n"
"    background-color: rgb(0, 170, 127);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.m2_btn1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2_btn1.sizePolicy().hasHeightForWidth())
        self.m2_btn1.setSizePolicy(sizePolicy)
        self.m2_btn1.setMinimumSize(QtCore.QSize(120, 45))
        self.m2_btn1.setMaximumSize(QtCore.QSize(16777215, 55))
        self.m2_btn1.setStyleSheet("")
        self.m2_btn1.setObjectName("m2_btn1")
        self.horizontalLayout.addWidget(self.m2_btn1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.m2_btn2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2_btn2.sizePolicy().hasHeightForWidth())
        self.m2_btn2.setSizePolicy(sizePolicy)
        self.m2_btn2.setMinimumSize(QtCore.QSize(120, 45))
        self.m2_btn2.setMaximumSize(QtCore.QSize(16777215, 55))
        self.m2_btn2.setStyleSheet("")
        self.m2_btn2.setObjectName("m2_btn2")
        self.horizontalLayout.addWidget(self.m2_btn2)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout.addWidget(self.frame_6)
        self.m2_btn3 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2_btn3.sizePolicy().hasHeightForWidth())
        self.m2_btn3.setSizePolicy(sizePolicy)
        self.m2_btn3.setMinimumSize(QtCore.QSize(120, 45))
        self.m2_btn3.setMaximumSize(QtCore.QSize(16777215, 55))
        self.m2_btn3.setStyleSheet("")
        self.m2_btn3.setObjectName("m2_btn3")
        self.horizontalLayout.addWidget(self.m2_btn3)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout.addWidget(self.frame_7)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.m2_p1 = QtWidgets.QLabel(self.page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.m2_p1.sizePolicy().hasHeightForWidth())
        self.m2_p1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.m2_p1.setFont(font)
        self.m2_p1.setStyleSheet("    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0, 168, 252);\n"
"    background-color: white;\n"
"    color: #d3dae3;")
        self.m2_p1.setText("")
        self.m2_p1.setObjectName("m2_p1")
        self.gridLayout_3.addWidget(self.m2_p1, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1043, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(3)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("font: 25 13pt \"Microsoft YaHei\";")
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.to_module1 = QtWidgets.QAction(MainWindow)
        self.to_module1.setObjectName("to_module1")
        self.to_module2 = QtWidgets.QAction(MainWindow)
        self.to_module2.setObjectName("to_module2")
        self.to_module3 = QtWidgets.QAction(MainWindow)
        self.to_module3.setObjectName("to_module3")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.data_select_xinyi = QtWidgets.QAction(MainWindow)
        self.data_select_xinyi.setObjectName("data_select_xinyi")
        self.data_select_yinshan = QtWidgets.QAction(MainWindow)
        self.data_select_yinshan.setObjectName("data_select_yinshan")
        self.menu.addAction(self.action1)
        self.menu.addAction(self.action2)
        self.menu_2.addAction(self.data_select_xinyi)
        self.menu_2.addAction(self.data_select_yinshan)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "输配协同下面向薄弱点关联潮流精准调控的多元用户联动决策支持系统"))
        self.label_6.setText(_translate("MainWindow", "输配协同下运行薄弱点关联潮流快速辨识与响应技术模块"))
        self.label_4.setText(_translate("MainWindow", "新能源消纳率响应前后可视图"))
        self.label.setText(_translate("MainWindow", "系统线路传输容量可视图"))
        self.label_2.setText(_translate("MainWindow", "新能源消纳率可视图"))
        self.m1_run1.setText(_translate("MainWindow", "运行"))
        self.m2_btn1.setText(_translate("MainWindow", "导入电网数据"))
        self.m2_btn2.setText(_translate("MainWindow", "导入运行数据"))
        self.m2_btn3.setText(_translate("MainWindow", "运行评估"))
        self.menu.setTitle(_translate("MainWindow", "功能模块"))
        self.menu_2.setTitle(_translate("MainWindow", "数据选择"))
        self.to_module1.setText(_translate("MainWindow", "模块一"))
        self.to_module2.setText(_translate("MainWindow", "模块二"))
        self.to_module3.setText(_translate("MainWindow", "模块三"))
        self.action1.setText(_translate("MainWindow", "模块一"))
        self.action2.setText(_translate("MainWindow", "模块二"))
        self.data_select_xinyi.setText(_translate("MainWindow", "xinyi"))
        self.data_select_yinshan.setText(_translate("MainWindow", "yinshan"))
