# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 925)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(3, 128, 125);\n"
"border-top-right-radius:15px;\n"
"border-top-left-radius:15px;\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(30, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_333 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_333.setFont(font)
        self.label_333.setStyleSheet("font: 75 12pt \"等线\";\n"
"color: rgb(255, 255, 255);")
        self.label_333.setObjectName("label_333")
        self.horizontalLayout_2.addWidget(self.label_333)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(170, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(83, 234, 178,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 160, 7,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/btn1.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(170, 50))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(170, 40))
        self.pushButton_2.setStyleSheet("QPushButton{background-color: rgba(85, 170, 255,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 160, 7,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/btn2.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(170, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_min = QtWidgets.QPushButton(self.widget)
        self.btn_min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon2)
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_3.addWidget(self.btn_min)
        self.btn_max = QtWidgets.QPushButton(self.widget)
        self.btn_max.setStyleSheet("QPushButton  hover{\n"
"    padding-top:3px;\n"
"    padding-right:3px;\n"
"\n"
"}")
        self.btn_max.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_max.setIcon(icon3)
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_3.addWidget(self.btn_max)
        self.btn_close = QtWidgets.QPushButton(self.widget)
        self.btn_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon4)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setStyleSheet("background-color: rgb(3, 128, 125);\n"
"border-color: rgb(85, 255, 255);\n"
"border-right:0px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_5)
        self.tabWidget.setStyleSheet("QTabWidget::pane {  \n"
"    border-top: 0px solid rgb(20,75,202);  \n"
"    position: absolute;  \n"
"    top: 0em;  \n"
"}  \n"
"  \n"
"QTabWidget::tab-bar {  \n"
"    alignment: left;  \n"
"}  \n"
"  \n"
"QTabBar::tab {  \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(3, 128, 125), stop:0.4 rgb(221, 221, 221), stop:0.5 rgb(216, 216, 216), stop:1.0 rgb(211, 211, 211));  \n"
"    border: 2px solid rgb(196, 196, 195);  \n"
"    border-bottom-color: rgb(3, 128, 125); /* same as the pane color */  \n"
"    border-top-left-radius: 4px;  \n"
"    border-top-right-radius: 4px;  \n"
"    min-width: 8ex;  \n"
"    padding: 2px;  \n"
"}  \n"
"  \n"
"QTabBar::tab:selected, QTabBar::tab:hover {  \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(250, 250, 250), stop:0.4 rgb(244, 244, 244), stop:0.5 rgb(231, 231, 231), stop:1.0 rgb(250, 250, 250));  \n"
"}  \n"
"  \n"
"QTabBar::tab:selected {  \n"
"    border-color: rgb(8, 255, 255);  \n"
"    border-bottom-color: rgb(3, 128, 125); /* same as pane color */ \n"
" \n"
"    background-color: rgb(8, 255, 255);\n"
"}  \n"
"  \n"
"QTabBar::tab:!selected {  \n"
"    margin-top: 2px; /* make non-selected tabs look smaller */  \n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.btn_img_6 = QtWidgets.QPushButton(self.tab)
        self.btn_img_6.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_6.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/btn345.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_img_6.setIcon(icon5)
        self.btn_img_6.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_6.setObjectName("btn_img_6")
        self.verticalLayout_30.addWidget(self.btn_img_6)
        self.widget_22 = QtWidgets.QWidget(self.tab)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_6 = QtWidgets.QLabel(self.widget_22)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_27.addWidget(self.label_6)
        self.verticalLayout_30.addWidget(self.widget_22)
        self.verticalLayout_31.addLayout(self.verticalLayout_30)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.btn_img_7 = QtWidgets.QPushButton(self.tab_3)
        self.btn_img_7.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_7.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_7.setText("")
        self.btn_img_7.setIcon(icon5)
        self.btn_img_7.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_7.setObjectName("btn_img_7")
        self.verticalLayout_32.addWidget(self.btn_img_7)
        self.widget_23 = QtWidgets.QWidget(self.tab_3)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_7 = QtWidgets.QLabel(self.widget_23)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_28.addWidget(self.label_7)
        self.verticalLayout_32.addWidget(self.widget_23)
        self.verticalLayout_33.addLayout(self.verticalLayout_32)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_6 = QtWidgets.QWidget(self.tab_4)
        self.widget_6.setStyleSheet("color: rgb(3, 128, 125);\n"
"border-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.widget_6)
        self.listWidget.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(85, 255, 255);\n"
"border-color: rgb(85, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_8.addWidget(self.widget_6)
        self.widget_9 = QtWidgets.QWidget(self.tab_4)
        self.widget_9.setStyleSheet("QWidget#widget_9{background-color: rgb(0, 0, 0);\n"
"border-color: rgb(85, 255, 255);}\n"
"")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.widget_9)
        self.label.setMinimumSize(QtCore.QSize(150, 70))
        self.label.setMaximumSize(QtCore.QSize(150, 70))
        self.label.setStyleSheet("font: 9pt \"等线\";\n"
"color: rgb(85, 255, 255);\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/label_2.gif"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addWidget(self.widget_10)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 15)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.btn_img_8 = QtWidgets.QPushButton(self.tab_2)
        self.btn_img_8.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_8.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_8.setText("")
        self.btn_img_8.setIcon(icon5)
        self.btn_img_8.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_8.setObjectName("btn_img_8")
        self.verticalLayout_34.addWidget(self.btn_img_8)
        self.widget_24 = QtWidgets.QWidget(self.tab_2)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_8 = QtWidgets.QLabel(self.widget_24)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_29.addWidget(self.label_8)
        self.verticalLayout_34.addWidget(self.widget_24)
        self.verticalLayout_35.addLayout(self.verticalLayout_34)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_12.addWidget(self.tabWidget)
        self.horizontalLayout_7.addWidget(self.widget_5)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.page)
        self.widget_4.setStyleSheet("background-color: rgb(3, 128, 125);")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.btn_img_1 = QtWidgets.QPushButton(self.widget_7)
        self.btn_img_1.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_1.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/btn3.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_img_1.setIcon(icon6)
        self.btn_img_1.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_1.setObjectName("btn_img_1")
        self.horizontalLayout_11.addWidget(self.btn_img_1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.btn_load_1 = QtWidgets.QPushButton(self.widget_7)
        self.btn_load_1.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_load_1.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_load_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/btn4.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_load_1.setIcon(icon7)
        self.btn_load_1.setIconSize(QtCore.QSize(150, 40))
        self.btn_load_1.setObjectName("btn_load_1")
        self.horizontalLayout_11.addWidget(self.btn_load_1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.btn_predict_1 = QtWidgets.QPushButton(self.widget_7)
        self.btn_predict_1.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_predict_1.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_predict_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/btn5.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_predict_1.setIcon(icon8)
        self.btn_predict_1.setIconSize(QtCore.QSize(150, 40))
        self.btn_predict_1.setObjectName("btn_predict_1")
        self.horizontalLayout_11.addWidget(self.btn_predict_1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_4)
        self.widget_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_image_1 = QtWidgets.QLabel(self.widget_8)
        self.label_image_1.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_image_1.setScaledContents(True)
        self.label_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_1.setObjectName("label_image_1")
        self.horizontalLayout_22.addWidget(self.label_image_1)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_11 = QtWidgets.QWidget(self.page_2)
        self.widget_11.setStyleSheet("background-color: rgb(3, 128, 125);\n"
"border-color: rgb(85, 255, 255);\n"
"border-right:0px;")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_15.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_15.setSpacing(1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_12 = QtWidgets.QWidget(self.widget_11)
        self.widget_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.widget_12)
        self.tabWidget_2.setStyleSheet("QTabWidget::pane {  \n"
"    border-top: 0px solid rgb(20,75,202);  \n"
"    position: absolute;  \n"
"    top: 0em;  \n"
"}  \n"
"  \n"
"QTabWidget::tab-bar {  \n"
"    alignment: left;  \n"
"}  \n"
"  \n"
"QTabBar::tab {  \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(3, 128, 125), stop:0.4 rgb(221, 221, 221), stop:0.5 rgb(216, 216, 216), stop:1.0 rgb(211, 211, 211));  \n"
"    border: 2px solid rgb(196, 196, 195);  \n"
"    border-bottom-color: rgb(3, 128, 125); /* same as the pane color */  \n"
"    border-top-left-radius: 4px;  \n"
"    border-top-right-radius: 4px;  \n"
"    min-width: 8ex;  \n"
"    padding: 2px;  \n"
"}  \n"
"  \n"
"QTabBar::tab:selected, QTabBar::tab:hover {  \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(250, 250, 250), stop:0.4 rgb(244, 244, 244), stop:0.5 rgb(231, 231, 231), stop:1.0 rgb(250, 250, 250));  \n"
"}  \n"
"  \n"
"QTabBar::tab:selected {  \n"
"    border-color: rgb(8, 255, 255);  \n"
"    border-bottom-color: rgb(3, 128, 125); /* same as pane color */ \n"
" \n"
"    background-color: rgb(8, 255, 255);\n"
"}  \n"
"  \n"
"QTabBar::tab:!selected {  \n"
"    margin-top: 2px; /* make non-selected tabs look smaller */  \n"
"}")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.btn_img_4 = QtWidgets.QPushButton(self.tab_5)
        self.btn_img_4.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_4.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_4.setText("")
        self.btn_img_4.setIcon(icon5)
        self.btn_img_4.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_4.setObjectName("btn_img_4")
        self.verticalLayout_26.addWidget(self.btn_img_4)
        self.widget_20 = QtWidgets.QWidget(self.tab_5)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_4 = QtWidgets.QLabel(self.widget_20)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_25.addWidget(self.label_4)
        self.verticalLayout_26.addWidget(self.widget_20)
        self.verticalLayout_27.addLayout(self.verticalLayout_26)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.btn_img_3 = QtWidgets.QPushButton(self.tab_6)
        self.btn_img_3.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_3.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_3.setText("")
        self.btn_img_3.setIcon(icon5)
        self.btn_img_3.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_3.setObjectName("btn_img_3")
        self.verticalLayout_24.addWidget(self.btn_img_3)
        self.widget_19 = QtWidgets.QWidget(self.tab_6)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_3 = QtWidgets.QLabel(self.widget_19)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_24.addWidget(self.label_3)
        self.verticalLayout_24.addWidget(self.widget_19)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_13 = QtWidgets.QWidget(self.tab_7)
        self.widget_13.setStyleSheet("color: rgb(3, 128, 125);\n"
"border-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.listWidget_2 = QtWidgets.QListWidget(self.widget_13)
        self.listWidget_2.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(85, 255, 255);\n"
"border-color: rgb(85, 255, 255);")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_15.addWidget(self.listWidget_2)
        self.horizontalLayout_16.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.tab_7)
        self.widget_14.setStyleSheet("QWidget#widget_9{background-color: rgb(0, 0, 0);\n"
"border-color: rgb(85, 255, 255);}\n"
"")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_2 = QtWidgets.QLabel(self.widget_14)
        self.label_2.setMinimumSize(QtCore.QSize(150, 70))
        self.label_2.setMaximumSize(QtCore.QSize(150, 70))
        self.label_2.setStyleSheet("font: 9pt \"等线\";\n"
"color: rgb(85, 255, 255);\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/label_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_17.addWidget(self.label_2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_19.addLayout(self.verticalLayout_21)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 1)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addWidget(self.widget_15)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 15)
        self.verticalLayout_16.addLayout(self.verticalLayout_17)
        self.horizontalLayout_16.addWidget(self.widget_14)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.btn_img_5 = QtWidgets.QPushButton(self.tab_8)
        self.btn_img_5.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_5.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_5.setText("")
        self.btn_img_5.setIcon(icon5)
        self.btn_img_5.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_5.setObjectName("btn_img_5")
        self.verticalLayout_28.addWidget(self.btn_img_5)
        self.widget_21 = QtWidgets.QWidget(self.tab_8)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_5 = QtWidgets.QLabel(self.widget_21)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_26.addWidget(self.label_5)
        self.verticalLayout_28.addWidget(self.widget_21)
        self.verticalLayout_29.addLayout(self.verticalLayout_28)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.verticalLayout_13.addWidget(self.tabWidget_2)
        self.horizontalLayout_15.addWidget(self.widget_12)
        self.horizontalLayout_14.addWidget(self.widget_11)
        self.widget_16 = QtWidgets.QWidget(self.page_2)
        self.widget_16.setStyleSheet("background-color: rgb(3, 128, 125);")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_22.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_22.setSpacing(1)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.widget_17 = QtWidgets.QWidget(self.widget_16)
        self.widget_17.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem10)
        self.btn_img_2 = QtWidgets.QPushButton(self.widget_17)
        self.btn_img_2.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_img_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_img_2.setText("")
        self.btn_img_2.setIcon(icon6)
        self.btn_img_2.setIconSize(QtCore.QSize(140, 40))
        self.btn_img_2.setObjectName("btn_img_2")
        self.horizontalLayout_20.addWidget(self.btn_img_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem11)
        self.btn_load_2 = QtWidgets.QPushButton(self.widget_17)
        self.btn_load_2.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_load_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_load_2.setText("")
        self.btn_load_2.setIcon(icon7)
        self.btn_load_2.setIconSize(QtCore.QSize(150, 40))
        self.btn_load_2.setObjectName("btn_load_2")
        self.horizontalLayout_20.addWidget(self.btn_load_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem12)
        self.btn_predict_2 = QtWidgets.QPushButton(self.widget_17)
        self.btn_predict_2.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_predict_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"    font: 9pt \"等线\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0,0);\n"
"border-radius:3px;\n"
"border-radius:3px;\n"
"font: 9pt \"等线\";\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_predict_2.setText("")
        self.btn_predict_2.setIcon(icon8)
        self.btn_predict_2.setIconSize(QtCore.QSize(150, 40))
        self.btn_predict_2.setObjectName("btn_predict_2")
        self.horizontalLayout_20.addWidget(self.btn_predict_2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.verticalLayout_23.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.widget_16)
        self.widget_18.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_image_2 = QtWidgets.QLabel(self.widget_18)
        self.label_image_2.setStyleSheet("color: rgb(226, 226, 226);")
        self.label_image_2.setScaledContents(True)
        self.label_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_2.setObjectName("label_image_2")
        self.horizontalLayout_23.addWidget(self.label_image_2)
        self.verticalLayout_23.addWidget(self.widget_18)
        self.verticalLayout_23.setStretch(0, 1)
        self.verticalLayout_23.setStretch(1, 7)
        self.verticalLayout_22.addLayout(self.verticalLayout_23)
        self.horizontalLayout_14.addWidget(self.widget_16)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_14)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 95)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_333.setText(_translate("MainWindow", "输配协同下面向薄弱点关联潮流精准调控的多元用户联动决策支持系统"))
        self.label_6.setText(_translate("MainWindow", "show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "电网数据"))
        self.label_7.setText(_translate("MainWindow", "show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "运行数据"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "负荷调控结果"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "节点边际电价"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "运行评估"))
        self.label_8.setText(_translate("MainWindow", "show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "结果检验"))
        self.label_image_1.setText(_translate("MainWindow", "图像展示"))
        self.label_4.setText(_translate("MainWindow", "show"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "电网数据"))
        self.label_3.setText(_translate("MainWindow", "show"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "运行数据"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "系统传输容量"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "新能源消纳率"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "消纳率响应前后对比"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "运行评估"))
        self.label_5.setText(_translate("MainWindow", "show"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "结果检验"))
        self.label_image_2.setText(_translate("MainWindow", "图像展示"))
import image_rc
